profile: private
region: us-east-1
configuration:
  name: lamvery-test-js
  runtime: nodejs
  role: {{ env['AWS_LAMBDA_ROLE'] }}
  handler: lambda_function.lambdaHandler
  description: This is sample lambda function.
  timeout: 10
  memory_size: 128
  vpc_config:
    subnets:
    - subnet-cadf2993
    security_groups:
    - sg-4d095028
