profile: null
region: us-east-1
versioning: true
default_alias: test
configuration:
  name: lamvery
  runtime: python2.7
  role: arn:aws:iam::<account-number>:role/<role>
  handler: lambda_function.lambda_handler
  description: This is a sample lambda function.
  timeout: 10
  memory_size: 128
events:
- rule: sample-rule-name
  description: This is a sample CloudWatchEvent
  schedule: rate(5 minutes)
  targets:
  - id: <unique-target-id>
    input:
      this:
      - is: a
      - sample: input
    input_path: json.path.format
secret:
  key_id: <key-id>
  cipher_texts: {}
exclude:
- ^\.lamvery\.yml$
