profile: null
region: us-east-1
versioning: true
default_alias: test
configuration:
  name: lamvery
  runtime: python2.7
  role: arn:aws:iam::<account-number>:role/<role>
  handler: lambda_function.lambda_handler
  description: This is a sample lambda function.
  timeout: 10
  memory_size: 128
  vpc_config:
    subnets:
    - subnet-xxxxxxxx
    security_groups:
    - sg-xxxxxxxx
